export const FETCH_ALL_DOGS_SUCCESS = 'FETCH_ALL_DOGS_SUCCESS';
export const FETCH_ALL_DOGS_ERROR = 'FETCH_ALL_DOGS_ERROR';

export const FETCH_RANDOM_TEXT_SUCCESS = 'FETCH_RANDOM_TEXT_SUCCESS';
export const FETCH_RANDOM_TEXT_ERROR = 'FETCH_RANDOM_TEXT_ERROR';

export const FETCH_BREAD_IMAGE_SUCCESS = 'FETCH_BREAD_IMAGE_SUCCESS';
export const FETCH_BREAD_IMAGE_ERROR = 'FETCH_BREAD_IMAGE_SUCCESS_ERROR';